# Generated by Django 5.1.2 on 2025-01-29 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iptv', '0002_alter_dvbt_channels_dvbt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Streams_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=254)),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Streams',
            fields=[
                ('udp_ip', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('udp_port', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=40)),
                ('type_content', models.CharField(max_length=15)),
                ('stream_list', models.ManyToManyField(to='iptv.streams_list')),
            ],
            options={
                'ordering': ['udp_ip', 'udp_port'],
            },
        ),
    ]
