# Generated by Django 5.1.2 on 2025-01-29 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iptv', '0003_streams_list_streams'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='streams',
            name='stream_list',
        ),
        migrations.AddField(
            model_name='streams_list',
            name='stream',
            field=models.ManyToManyField(to='iptv.streams'),
        ),
    ]
