# Generated by Django 5.1.2 on 2025-01-30 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iptv', '0004_remove_streams_stream_list_streams_list_stream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dvbt_channels',
            name='dvbt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dvbt_channels', to='iptv.dvbt'),
        ),
        migrations.CreateModel(
            name='Dvbt_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('sid', models.CharField(max_length=5)),
                ('udp_ip', models.CharField(blank=True, max_length=15)),
                ('udp_port', models.CharField(blank=True, max_length=5)),
                ('dvbt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dvbt_list', to='iptv.dvbt')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
