# Generated by Django 5.1.2 on 2025-01-30 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iptv', '0005_alter_dvbt_channels_dvbt_dvbt_list'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dvbt_Channels',
        ),
    ]
