# Generated by Django 5.1.2 on 2025-01-31 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iptv', '0008_alter_dvbt_list_dvbt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dvbt',
            options={'ordering': ['name']},
        ),
    ]
