# Generated by Django 5.1.2 on 2025-01-31 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iptv', '0009_alter_dvbt_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dvbt',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Вкл_Выкл'),
        ),
        migrations.AlterField(
            model_name='dvbt',
            name='freq',
            field=models.CharField(max_length=3, verbose_name='Частота'),
        ),
        migrations.AlterField(
            model_name='dvbt',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Канал'),
        ),
    ]
