# Generated by Django 5.1.2 on 2025-01-31 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iptv', '0011_remove_streams_list_stream_streams_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streams',
            name='content',
            field=models.ManyToManyField(related_name='stream', to='iptv.streams_list'),
        ),
    ]
