# Generated by Django 5.1.5 on 2025-02-01 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iptv', '0012_alter_streams_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('udp_ip', models.CharField(max_length=15, verbose_name='IP адрес')),
                ('udp_port', models.CharField(blank=True, max_length=5, verbose_name='IP порт')),
                ('name', models.CharField(blank=True, max_length=40, verbose_name='Примечание')),
                ('type_content', models.CharField(blank=True, max_length=15, verbose_name='Тип контента')),
            ],
            options={
                'ordering': ['udp_ip', 'udp_port'],
            },
        ),
        migrations.DeleteModel(
            name='Streams',
        ),
        migrations.DeleteModel(
            name='Streams_List',
        ),
    ]
