# Generated by Django 5.1.5 on 2025-02-01 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iptv', '0013_stream_delete_streams_delete_streams_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='Streams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('udp_ip', models.CharField(max_length=15, verbose_name='IP адрес')),
                ('udp_port', models.CharField(blank=True, max_length=5, verbose_name='IP порт')),
                ('name', models.CharField(blank=True, max_length=40, verbose_name='Примечание')),
                ('type_content', models.CharField(blank=True, max_length=15, verbose_name='Тип контента')),
            ],
            options={
                'ordering': ['udp_ip', 'udp_port'],
            },
        ),
        migrations.CreateModel(
            name='Streams_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, max_length=254, verbose_name='Контент')),
                ('name', models.CharField(blank=True, max_length=40, verbose_name='Примечание')),
            ],
        ),
        migrations.DeleteModel(
            name='Stream',
        ),
        migrations.AddField(
            model_name='streams',
            name='content',
            field=models.ManyToManyField(related_name='stream', to='iptv.streams_list'),
        ),
    ]
