# Generated by Django 5.1.5 on 2025-02-01 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iptv', '0015_alter_streams_udp_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='streams',
            name='content',
        ),
        migrations.AddField(
            model_name='streams_list',
            name='streams',
            field=models.ManyToManyField(related_name='content', to='iptv.streams'),
        ),
    ]
