# Generated by Django 5.1.5 on 2025-02-01 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iptv', '0016_remove_streams_content_streams_list_streams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streams_list',
            name='streams',
            field=models.ManyToManyField(to='iptv.streams'),
        ),
    ]
