# Generated by Django 5.1.5 on 2025-02-01 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iptv', '0017_alter_streams_list_streams'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='streams_list',
            name='streams',
        ),
        migrations.AddField(
            model_name='streams',
            name='contebt',
            field=models.ManyToManyField(to='iptv.streams_list'),
        ),
    ]
