# Generated by Django 5.1.5 on 2025-02-01 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iptv', '0018_remove_streams_list_streams_streams_contebt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='streams',
            old_name='contebt',
            new_name='content',
        ),
    ]
