# Generated by Django 5.1.2 on 2025-02-03 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iptv', '0019_rename_contebt_streams_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='streams_list',
            options={'ordering': ['source']},
        ),
    ]
