# Generated by Django 5.1.2 on 2025-02-03 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iptv', '0020_alter_streams_list_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streams',
            name='name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Примечание'),
        ),
    ]
