# Generated by Django 5.1.2 on 2025-02-03 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iptv', '0021_alter_streams_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stb_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=20, verbose_name='Модель')),
                ('name', models.CharField(max_length=30, verbose_name='Примечание')),
                ('login', models.CharField(max_length=20, verbose_name='Логин')),
                ('password', models.CharField(max_length=30, verbose_name='Пароль')),
                ('templ', models.CharField(max_length=30, verbose_name='Шаблон')),
            ],
        ),
        migrations.AlterField(
            model_name='streams',
            name='type_content',
            field=models.CharField(blank=True, max_length=10, verbose_name='Тип контента'),
        ),
    ]
