# Generated by Django 5.1.2 on 2025-02-03 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iptv', '0022_groups_stb_type_alter_streams_type_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='start_stream',
            field=models.CharField(default='224.10.10.10', max_length=20, verbose_name='Старт канал'),
        ),
        migrations.AlterField(
            model_name='dvbt',
            name='freq',
            field=models.CharField(max_length=3, verbose_name='Частота'),
        ),
        migrations.AlterField(
            model_name='dvbt',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Канал'),
        ),
        migrations.AlterField(
            model_name='dvbt_list',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Программа'),
        ),
        migrations.AlterField(
            model_name='dvbt_list',
            name='sid',
            field=models.CharField(max_length=5, verbose_name='SIG'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='Имя группы'),
        ),
        migrations.AlterField(
            model_name='streams',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='streams',
            name='type_content',
            field=models.CharField(max_length=10, verbose_name='Тип контента'),
        ),
        migrations.AlterField(
            model_name='streams',
            name='udp_port',
            field=models.CharField(max_length=5, verbose_name='IP порт'),
        ),
        migrations.AlterField(
            model_name='streams_list',
            name='source',
            field=models.CharField(max_length=254, verbose_name='Контент'),
        ),
    ]
