# Generated by Django 5.1.2 on 2025-02-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iptv', '0023_groups_start_stream_alter_dvbt_freq_alter_dvbt_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='start_stream',
            field=models.CharField(blank=True, max_length=20, verbose_name='Старт канал'),
        ),
    ]
