# Generated by Django 5.1.2 on 2025-02-04 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iptv', '0025_remove_stb_type_templ_remove_streams_type_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stb_type',
            name='remote_control',
            field=models.CharField(default='ssh', max_length=15, verbose_name='Удаленный доступ'),
        ),
        migrations.CreateModel(
            name='Stb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(max_length=17, verbose_name='MAC адрес')),
                ('ip_address', models.CharField(max_length=15, verbose_name='MAC адрес')),
                ('place', models.CharField(max_length=30, verbose_name='Место установки')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stb_list', to='iptv.groups', verbose_name='Группа')),
                ('stb_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stb_list', to='iptv.stb_type', verbose_name='Тип')),
            ],
        ),
    ]
