# Generated by Django 5.1.2 on 2025-02-04 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iptv', '0028_alter_dvbt_list_dvbt_alter_stb_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stb',
            name='stb_type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='stb_type', to='iptv.stb_type', verbose_name='Тип'),
        ),
    ]
