# Generated by Django 5.1.2 on 2025-02-04 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iptv', '0029_alter_stb_stb_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stb',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='stb_list', to='iptv.groups', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='stb',
            name='stb_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='stb_type', to='iptv.stb_type', verbose_name='Тип'),
        ),
    ]
