# Generated by Django 5.1.2 on 2025-02-05 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iptv', '0030_alter_stb_group_alter_stb_stb_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='streams',
            options={'ordering': ['udp_ip']},
        ),
        migrations.AlterField(
            model_name='dvbt_list',
            name='name',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Программа'),
        ),
        migrations.AlterField(
            model_name='stb',
            name='ip_address',
            field=models.CharField(db_index=True, max_length=15, verbose_name='IP адрес'),
        ),
        migrations.AlterField(
            model_name='stb',
            name='mac_address',
            field=models.CharField(db_index=True, max_length=17, verbose_name='MAC адрес'),
        ),
        migrations.AlterField(
            model_name='stb',
            name='place',
            field=models.CharField(db_index=True, max_length=30, verbose_name='Место установки'),
        ),
        migrations.AlterField(
            model_name='streams',
            name='udp_ip',
            field=models.CharField(db_index=True, max_length=15, verbose_name='IP адрес'),
        ),
    ]
