# Generated by Django 5.1.2 on 2025-02-05 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iptv', '0031_alter_streams_options_alter_dvbt_list_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='streams',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stream', to='iptv.groups', verbose_name='Группа'),
        ),
    ]
