# Generated by Django 5.1.2 on 2025-02-05 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iptv', '0032_streams_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streams',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='stream', to='iptv.groups', verbose_name='Группа'),
        ),
    ]
