# Generated by Django 5.1.2 on 2025-02-05 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iptv', '0033_alter_streams_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dvbt_list',
            name='dvbt',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='dvbt_ch', to='iptv.dvbt', verbose_name='Канал'),
        ),
        migrations.AlterField(
            model_name='stb',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stb_list', to='iptv.groups', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='stb',
            name='stb_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stb_type', to='iptv.stb_type', verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='streams',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stream', to='iptv.groups', verbose_name='Группа'),
        ),
    ]
