# Generated by Django 5.1.2 on 2025-02-06 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iptv', '0034_alter_dvbt_list_dvbt_alter_stb_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stb_type',
            name='template',
        ),
        migrations.AddField(
            model_name='stb_type',
            name='temp_dhcp',
            field=models.CharField(blank=True, max_length=20, verbose_name='Шаблон DHCP'),
        ),
        migrations.AddField(
            model_name='stb_type',
            name='temp_html',
            field=models.CharField(blank=True, max_length=20, verbose_name='Шаблон HTML'),
        ),
    ]
